# Server configuration
server:
  port: 8081  # Port where the Employee Service runs

# Spring Boot application database configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_db?createDatabaseIfNotExist=true  # JDBC URL for MySQL database
    username: root  # Database username
    password: Admin123!  # Database password
  jpa:
    hibernate:
      ddl-auto: update  # Automatically update the DB schema based on entities

# Custom application property
properties:
  message: Hello From Employee Service - Spring cloud bus demo  # Example message used for config refresh demo
