# Server configuration
server:
  port: 8083  # Port where the Organization Service runs

# Spring Boot application database configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/organization_db?createDatabaseIfNotExist=true  # JDBC URL for MySQL database
    username: root  # Database username
    password: Admin123!  # Database password
  jpa:
    hibernate:
      ddl-auto: update  # Automatically update the DB schema based on entities

# Eureka client configuration
eureka:
  instance:
    hostname: localhost  # Hostname used for Eureka registration
    prefer-ip-address: false  # Prefer hostname over IP
    instance-id: ${spring.application.name}:${random.value}  # Unique instance ID using app name and random value